### ISSUE TITLE
Does not use cli configured --skip-ssl-validation for target 

### ISSUE THREAD

**Issue by zrob** [cloudfoundry-incubator/cflocal#1]
I tried pulling an app from my local bosh-lite.  Ran into a cert error.  I'm just guessing, put may want to take a look at this from the cli plugin interface: https://github.com/cloudfoundry/cli/blob/master/plugin/plugin.go#L26

PS: this looks pretty sweet and looking forward to playing with it a bit

**Comment by sclevine** [comment]
Thanks for the report @zrob, fixed in [v0.5.0](https://github.com/sclevine/cflocal/releases/tag/v0.5.0).
