### ISSUE TITLE
Installation Failed: fork/exec ./cflocal: no such file or directory

### ISSUE THREAD

**Issue by manjunathgudisi** [cloudfoundry-incubator/cflocal#11]
Hi 

Installation is failed due to below error.

> fork/exec ./cflocal: no such file or directory

Attached the screenshot.
![screen shot 2017-10-22 at 10 57 17 am](https://user-images.githubusercontent.com/6059076/31858553-16e1f216-b718-11e7-9014-214e4b2988fa.jpg)

Thanks, MG

**Comment by sclevine** [comment]
I suspect that you're running an old version of the cf CLI. See #6.

**Comment by sclevine** [comment]
Were you able to get past this issue?

**Comment by manjunathgudisi** [comment]
yes, I have updated the cf-cli to

> cf version 6.32.0+0191c33d9.2017-09-26

and then installed cflocal. Works fine. 

> Plugin cflocal 0.18.0 successfully installed

Thank you.
