### ISSUE TITLE
cf install-plugin failure creating temp directory

### ISSUE THREAD

**Issue by seanwolfecsaa** [cloudfoundry-incubator/cflocal#17]
```
11:11 $ cf install-plugin cflocal
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin cflocal? [yN]: y
mkdir /Users/gslzwol/.cf/plugins/temp255375442/361314697: not a directory
FAILED
✘-1 ~/work 
11:11 $ 
```

looks like the mkdir command needs a ```mkdir -p``` ?

OSX 10.11.6, cf version 6.29.1+d5129d651.2017-08-17

I'll try updating cf.

```
11:15 $ cf install-plugin cflocal
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin cflocal? [yN]: y
mkdir /Users/gslzwol/.cf/plugins/temp013336009/491367060: not a directory
FAILED
✘-1 ~/work 
11:15 $ cf version
cf version 6.34.0+f53d03a5e.2018-01-09
```

Still failing with the latest cf-cli version.

**Comment by sclevine** [comment]
Hi @seanwolfecsaa,

The CF Local plugin has no control over this behavior. Are you able to install any other cf CLI plugins? 

https://github.com/cloudfoundry/cli/issues/1259 suggests that you are attempting to run `cf install-plugin` with a directory called `cflocal` in the current working directory. If that's the case, try changing the directory you run `cf install-plugin` from, or run `cf install-plugin` on a release binary instead of on a directory called `cflocal`.

**Comment by seanwolfecsaa** [comment]
Ah, looks like the problem is with the main CF toolset. We can close this issue.

**Comment by sclevine** [comment]
As suggested in https://github.com/cloudfoundry/cli/issues/1259, the error occurs when you run `cf install-plugin` with a directory in your working directory that has the same name as the plugin you're trying to install from the plugin repository. This is not a bug in the cf CLI -- more like an unclear error message. Were you able to get past the issue by installing the plugin from a different directory?

**Comment by seanwolfecsaa** [comment]
Seems like a pretty straighforward directory creation bug from the output -- can't create nested temporary subdirs and the script needs to use mkdir -p. I just downloaded the installation binary from the releases page. 👍 TIL that Github has a releases page, haha :octocat:
