### ISSUE TITLE
Service connections fail to skip ssl validation even when cf cli is configured to skip ssl validation

### ISSUE THREAD

**Issue by ssisil** [cloudfoundry-incubator/cflocal#18]
```Error: Get https://api.v2.pcfdev.io/v2/info: x509: certificate signed by unknown authority```

Remote app object should not use default http client

**Comment by sclevine** [comment]
Fixed in [v0.19.0](https://github.com/cloudfoundry-incubator/cflocal/releases/tag/v0.19.0).
