### ISSUE TITLE
Add plugin to https://plugins.cloudfoundry.org/

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cflocal#2]
See https://github.com/cloudfoundry-incubator/cli-plugin-repo for instructions
Perhaps you will want to include the un-compressed versions of plugins in your github releases so that you can link them directly into the plugins YAML file above.

**Comment by sclevine** [comment]
Done: https://github.com/cloudfoundry-incubator/cli-plugin-repo/pull/118
