### ISSUE TITLE
run <app name> -s <remote app name> -t throws a FAIL message

### ISSUE THREAD

**Issue by ssisil** [cloudfoundry-incubator/cflocal#20]
When running `cf local run <app name> -s <remote app name> -t` I consistently get this error message 

```
Running <app name> on port 63922...
Error: Error response from daemon: no such exec
FAILED
```

**Comment by sclevine** [comment]
Fixed in [v0.19.0](https://github.com/cloudfoundry-incubator/cflocal/releases/tag/v0.19.0).
