### ISSUE TITLE
cf local run -d with php won't start

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry-incubator/cflocal#29]
Reproduce:

``` sh
git clone git@github.com:18F/cf-hello-worlds.git
cd cf-hello-worlds/php

cat <<END> local.yml
applications:
- name: php
  memory: 256M
  buildpack: php_buildpack
  command: /bin/echo
END

cf local stage php
cf local run php -d .
```

Expected result: echo and then exit

Actual result:

```
$ cf local run php -d .
Running php on port 63178...
[php] 2019-01-17T23:52:35.787904900Z bash: /home/vcap/app/.bp/bin/start: No such file or directory
```

Is there a way for start command to be honored, or to otherwise avoid this error?

**Comment by pburkholder** [comment]
A bit more context:  

Hi Steve & folks: I've been poking at `cf local` since I'm trying to address the cloud.gov customers that are interested in running Drupal. Drupal is _not_ a cloud-friendly application, since it evolved to allow administrators to make changes to the local (presumed-presistent) filesystem directly through an admin UI. So, getting Drupal to run is easy, but's its a bit tricky devising a development process that is tractable and provides consistent results between a local development environment and a CF install.

At https://github.com/18F/nsf we have a pretty good process using docker-compose to create a local dev environment, where we capture local changes to files, commit to Git, then `cf push`.  But the Drupal that runs in Docker is not _identical_ to the what runs in CF - since it's not built up through the buildpack process. 

That's where I thought `cf local` would be cool, so we could do either `cf local stage` or `cf local pull`, then run `cf local run -d .` with the appropriate `local.yml`  But local run doesn't work since we're missing the `.bp/` directory and other environment configuration steps.

Do you think `cf local` is still feasible for this use case, or should we pursue docker-compose or other avenues?

**Comment by sclevine** [comment]
Hi @pburkholder,

As you've noticed, `cf local run -d` is imperfect -- it only works with an already-staged app. You could pull the already-staged app out of a pre-staged droplet, but then you'd have a bunch of junk in your git repo. This is currently the only solution.

Development efforts for cf local are currently directed at the Cloud Native Buildpacks CNCF Sandbox project (https://buildpacks.io). When all of the Cloud Foundry buildpacks are converted to the [CNB v3 API spec](https://github.com/buildpack/spec), CF Local will become a wrapper for the [pack CLI](https://github.com/buildpack/pack). The CNB v3 API has a [development API](https://github.com/buildpack/spec/blob/master/buildpack.md#development-setup) designed for local iteration, so we should have a robust solution for this eventually.
