### ISSUE TITLE
Add support for cflinuxfs3

### ISSUE THREAD

**Issue by marksjwhite** [cloudfoundry-incubator/cflocal#31]
With many CF environments now running cflinuxfs3 as their default stack, cflocal should give an option to specify the stack that it uses for its local runtime droplet image

cf local pull'ing some apps (such as node apps) already running on CF environments as cflinuxfs3, causes failure to start with errors like this, 

```
2019-02-01T10:48:53.005883844Z node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by node)
2019-02-01T10:48:53.005944899Z node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
```

```
$ cf local version
CF Local version 0.19.0
```
Thx

**Comment by sclevine** [comment]
Hi @marksjwhite,

Development efforts for CF Local are currently directed at the Cloud Native Buildpacks CNCF Sandbox project (https://buildpacks.io). When all of the Cloud Foundry buildpacks are converted to the [CNB v3 API spec](https://github.com/buildpack/spec), CF Local will become a wrapper for the [pack CLI](https://github.com/buildpack/pack).

I may swap cflinuxfs2 for cflinuxfs3 in CF Local before then, but given that the CF buildpacks are quickly being converted to CNBs, I'm not sure if it's worth it. Either way, CF Local will likely be updated within the next few months.

**Comment by williammartin** [comment]
I am also experiencing this issue and we don't seem to have a properly functioning v3 cf ruby buildpack yet.
