### ISSUE TITLE
Upgrade cflinuxfs2 to cflinuxfs3

### ISSUE THREAD

**Issue by joaquinito01** [cloudfoundry-incubator/cflocal#37]
Please, upgrade cflinuxfs2 to cflinuxfs3, please, the Cloud Foundry buildpacks does not work with me because needs cflinuxfs3.

**Comment by sclevine** [comment]
Merged: https://github.com/cloudfoundry-incubator/cflocal/pull/39

Please see the comments here about the future of CF Local: https://github.com/cloudfoundry-incubator/cflocal/issues/31#issuecomment-460466292
