### ISSUE TITLE
support for -p option for Spring boot

### ISSUE THREAD

**Issue by alexvasseur** [cloudfoundry-incubator/cflocal#4]
for Spring boot app, I would use `cf push -p myapp.jar appname` and there is no such a thing as the application folder

cf local is not friendly to that - is there some way to deal with that using `local.yml` (I could not find its expected structure) or a way to add the `-p` option ?

**Comment by sclevine** [comment]
Currently, you must unzip the JAR file and use CF Local from inside the unzipped folder.

The roadmap for extra local-path-related options looks like:
1. A `path` field in local.yml that allows you to specify a ZIP/JAR
2. A `-f` flag that allows you to specify a local.yml file
3. A `remote` field in local.yml that allows you to specify a different remote app name
4. A `droplet` field in local.yml that allows you to specify a droplet file

And then potentially:
1. A `-p` flag to override `path`
2. A `-n` flag to override `remote`
3. A `-d` flag to override `droplet`

**Comment by sclevine** [comment]
@avasseur-pivotal I added `-p` in the latest release (0.11.0).
