### ISSUE TITLE
'port' env variable not correct

### ISSUE THREAD

**Issue by mattmcneeney** [cloudfoundry-incubator/cflocal#7]
When running an application using `cf local run <name>`, if the application logs the `port` environmental variable, then this does not match the port the application is actually running on. I tested this using the [overview-broker](https://github.com/mattmcneeney/overview-broker) app, which produced the output below:
```
❯ cf local run overview-broker
Running overview-broker on port 53966...
[overview-broker] 2017-10-13T10:53:12.080513492Z
[overview-broker] 2017-10-13T10:53:12.080581011Z > overview-broker@1.0.0 start /home/vcap/app
[overview-broker] 2017-10-13T10:53:12.080588702Z > node index.js
[overview-broker] 2017-10-13T10:53:12.528347006Z Overview broker running on port 8080
```

This isn't super important and may even be desired behaviour, but just wanted to let you know in case this shouldn't be happening!

**Comment by sclevine** [comment]
Thanks for the report @mattmcneeney!

The current behavior is both desired and necessary. The internal container port in both Diego and CF Local is `8080`. The external port is just a way to expose the Docker container to the host.

**Comment by mattmcneeney** [comment]
Alright, good to know. Thanks for the swift response. Loving the plugin by the way!

**Comment by sclevine** [comment]
😄
