### ISSUE TITLE
push a staged app to ... XYZ ?

### ISSUE THREAD

**Issue by pourquoi42** [cloudfoundry-incubator/cflocal#9]
One of the features is "Stage apps with Docker and push them to a remote Cloud Foundry."

This made me wonder: when I have a docker container, couldn't I also push it elsewhere? Let's say kubernetes or dockerswarm?

**Comment by sclevine** [comment]
Yep, you can use `cf local export` to do this.

That said, k8s and Docker Swarm don't support upgrading the OS-level dependencies of live-running apps automatically, so you would need to re-run `cf local stage`, re-run `cf local export`, and push your new image to k8s/DS every time a USN comes out to achieve the same level of security. (This is one reason why CF is awesome.)

**Comment by pourquoi42** [comment]
awesome, thanks.

In my understanding, the approach of K8s to deal with security fixes on OS-level dependencies is simply to do a rolling upgrade of the apps deployed. True, that means the image would have to be rebaked from scratch first.
